@startuml

title leekwars - files dependencies

allowmixing

package engine {
  package round {
    class Round
    class LeekRound
    class CellRound
    class ToolRound
    class Action
  }
  class Board
  class Cell 
  class Leek
  class Effect
  class Tool
  frame const
  frame effectfunctions
  class EffectResult
  class InterCellInfo
  class Strategy
  class Talk
}

frame main

package utils {
  class GameDebug
  class Objects
  class Chain
  frame functions
}

main -> GameDebug
main --> Strategy
Strategy --> Board
Strategy -> Talk
LeekRound --> Action
Effect --> effectfunctions
Board --> EffectResult
Board --> Round 
Board --> const
Round --> CellRound
Round --> LeekRound
Board --> Cell
Cell --> InterCellInfo
LeekRound --> ToolRound
Leek --> Tool
Board --> Leek
Tool --> Effect
GameDebug --> Objects
GameDebug --> Chain
GameDebug --> functions

@enduml
