@startuml

title leekwars - files dependencies

allowmixing

class Round
class Board
package const
class Cell 
class Leek
class Effect
class Tool
package effectfunctions
class EffectResult
class InterCellInfo
class RelativeCell
class Strategy
package v3
class GameDebug
class LeekRound
class CellRound
class ToolRound
class Simulation
class Action
class Talk

v3 -> GameDebug
v3 --> Strategy
Strategy --> Simulation
Strategy -> Talk
Simulation --> Action
Simulation --> Board
Simulation --> effectfunctions
Simulation --> EffectResult
Simulation --> Round 
Simulation --> const
Simulation --> CellRound
Simulation --> LeekRound
Simulation --> Cell
Simulation --> InterCellInfo
Simulation --> ToolRound
Simulation --> Tool
Simulation --> Leek
Simulation --> Effect
Simulation --> RelativeCell

@enduml
