@startuml

title leekwars - files dependencies

allowmixing

class Round
class Board
class Cell 
class Leek
class Effect
class Tool
package const
package effectfunctions
class EffectResult
class InterCellInfo
class RelativeCell
class Strategy
package v3
class GameDebug
class LeekRound
class CellRound
class ToolRound
class Action
class Talk

v3 -> GameDebug
v3 --> Strategy
Strategy --> Board
Strategy -> Talk
Board --> Action
Board --> effectfunctions
Board --> EffectResult
Board --> Round 
Board --> const
Round --> CellRound
Round --> LeekRound
Board --> Cell
Cell --> InterCellInfo
Round --> ToolRound
Board --> Tool
Board --> Leek
Board --> Effect
Board --> RelativeCell

@enduml
