@startuml

title leekwars - files dependencies

allowmixing

package engine {
  package round {
    class Round
    class LeekRound
    class CellRound
    class ToolRound
  }
  class Board
  class Cell 
  class Leek
  class Effect
  class Tool
  frame const
  frame effectfunctions
  class EffectResult
  class InterCellInfo
  class RelativeCell
  class Strategy
  class Action
  class Talk
}

frame main

package utils {
  class GameDebug
  class Objects
  class Chain
  frame functions
}

main -> GameDebug
main --> Strategy
Strategy --> Board
Strategy -> Talk
Board --> Action
Board --> effectfunctions
Board --> EffectResult
Board --> Round 
Board --> const
Round --> CellRound
Round --> LeekRound
Board --> Cell
Cell --> InterCellInfo
Round --> ToolRound
Board --> Tool
Board --> Leek
Board --> Effect
Board --> RelativeCell
GameDebug --> Objects
GameDebug --> Chain
GameDebug --> functions

@enduml
